#!/bin/bash

BASE_DIR=/home/localhost/pa1850co-s/Desktop/BoC/caffe_training
SCR_DIR=$BASE_DIR/automation
LOGDIR=$BASE_DIR/log
CAFFEDIR=/home/localhost/pa1850co-s/caffe

SOLVER=$BASE_DIR/solver_transfer.prototxt
WEIGHTS=$BASE_DIR/snapshot_iter_300280.caffemodel
NET=$LOGDIR/trainedNet.log

usage() {
    echo "Specify no option to train the model or"
    echo "-plot to only plot the trained model"
}

refresh_log() {
  while [ true ]; do
    python $CAFFEDIR/tools/extra/parse_log.py $NET $LOGDIR
    sleep 5 
  done
}

plot() {
    cat <<EOF > $SCR_DIR/gnuplot_commands
# gnuplot_commands
set datafile separator ','
set multiplot
set grid

# Loss plot
set size 0.85,0.5
set origin 0.1,0.0
set yrange [0:*]
plot "$LOGDIR/trainedNet.log.train" using 1:5 lt rgb "blue" lw 2  with line title "training loss",\
     "$LOGDIR/trainedNet.log.test" using 1:5  lt rgb "red" lw 2 with line title "test loss"

# Accuracy plot
set size 0.85,0.5
set origin 0.1,0.5
set yrange [0:*]
plot "$LOGDIR/trainedNet.log.train" using 1:4  lt rgb "blue" lw 2 with line title "training accuracy",\
     "$LOGDIR/trainedNet.log.test" using 1:4  lt rgb "red" lw 2 with line title "test accuracy"
pause 1
reread

EOF
    refresh_log & 
    sleep 1
    gnuplot $SCR_DIR/gnuplot_commands
}

if  [ 1$1 = 1 ]
then
    #Train the model
    caffe train -gpu 0 -solver $SOLVER  -weights $WEIGHTS 2>&1 | tee $NET &
    
    plot
else
    if [ $1 = "-plot" ]
    then
	plot
    else
	echo "Error: wrong option specified"
	usage
    fi
fi
